# Generated by Django 3.2.25 on 2024-03-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_slug'),
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='orders.orderitem')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
            ],
        ),
    ]
