# Generated by Django 3.2.25 on 2024-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20240316_1547'),
        ('orders', '0005_orderitemspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, to='products.AttributeValue'),
        ),
    ]
