# Generated by Django 3.2.25 on 2024-03-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_attribute_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemSpecification',
        ),
    ]
