# Generated by Django 3.2.25 on 2024-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240313_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificationvalue',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
