# Generated by Django 3.2.25 on 2024-03-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_orderitemspecification'),
        ('products', '0013_auto_20240316_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specification',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.DeleteModel(
            name='ProductSpecificationValue',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
